In [1]:
import numpy as np


In [2]:
arr = [1,2,3,4]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)

In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape) #for the number of items

(4,)


In [8]:
print(a.dtype)

int32


In [9]:
#To get the dimension with ndim
print(a.ndim)

1


In [10]:
#Combining two arrays

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
#To know the dimension
print(b.ndim)

2


In [12]:
print(b.shape) #The shape of the matrix is two rows, three columns

(2, 3)


In [13]:
#There are also some inbuilt functions that can be used to initialize numpy which include empty(), 
#zeros(), ones(), full(), random.random().

#To generate a matrix with random value

np.random.random((2,3))


array([[0.23793721, 0.59136142, 0.51556829],
       [0.6474202 , 0.00176253, 0.32927661]])

In [14]:
#For array of Zeros

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#array of ones

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#For identity matrix

np.zeros((3))

array([0., 0., 0.])

In [17]:
#Operations in Array

c = np.array ([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array ([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])


In [18]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [19]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [20]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [21]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [22]:
#Indexing

a[0]


1

In [23]:
a[3]

4

In [24]:
b[0, 0]

1

In [25]:
b[1, 2]

6

In [26]:
c[0, 1]

8.0

In [27]:
#Slicing

d[1, 0:2]

array([9., 8.])

In [28]:
e = np.array ([[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]])

In [43]:
print(e)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [30]:
e[1:2, :2]

array([[14, 15]])

In [32]:
#boolean indexing

e[e>15]

array([16, 17, 18, 19, 20, 21])